name: CI

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-3.3.4
          bundler-cache: true

      - name: Lint code for consistent style
        run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      RAILS_APP_ENV: sandbox
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.3'
          - '3.2'
          - '3.1'
        rails:
          - r7
          - r71
          - r72
          - r8
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          rubygems: latest
        env:
          BUNDLE_GEMFILE: gemfiles/${{ matrix.rails }}.gemfile

      - name: Run tests
        env:
          RAILS_APP_ENV: sandbox
          BUNDLE_GEMFILE: gemfiles/${{ matrix.rails }}.gemfile
        run: bin/rails test
